### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by thijstriemstra** [versioduo/V2Potentiometer#1]
This code looks interesting but hard to digest without a simple example. Could you add one?

**Comment by kaysievers** [comment]
(Sorry, I never got a notification for this. Just noticed it now.)

Here is code using it, a 16 channel analog input MIDI controller:
  https://github.com/versioduo/express/blob/master/express.ino#L89

Here is the hardware:
  https://versioduo.com/#express

**Comment by thijstriemstra** [comment]
@kaysievers can you add that info to the readme?
